# $schema=https://www.schemastore.org/github-workflow.json
name: verify codebase health
on:
  schedule:
    - cron: 0 0 * * * # nightly
permissions:
  contents: read
jobs:
  verify-codebase-health:
    runs-on: ubuntu-latest
    steps:
      - name: checkout codebase
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: prepare development environment
        uses: jetify-com/devbox-install-action@8c6a66ed6273138b1915457069de78cb52fe3bd7 # v0.15.0
        with:
          enable-cache: true
          devbox-version: 0.17.5
          sha256-checksum: 520abeaca5fb8e8175bea2acdaac4109e87768ac25ad8da5ad2e6eace5a6060b #devbox_0.17.5_linux_amd64.tar.gz

      - name: get current date
        id: date
        shell: bash
        run: echo "date=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"

      - name: load cache for link validation checks
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ./.lycheecache
          key: cache-lychee-${{ steps.date.outputs.date }}-v1
          restore-keys: cache-lychee-

      - name: load cache for vulnerability audit database
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ./.task/cache/trivy
          key: cache-trivy-${{ steps.date.outputs.date }}-v1
          restore-keys: cache-trivy-

      - run: devbox run task --verbose verify:codebase-health
